#!/usr/bin/env python3
from __future__ import annotations

import argparse
import struct
from pathlib import Path


BACKUP_SUFFIX = ".orig_cop_livery_country_prod2"
DEFAULT_EXE_GLOB = "PROD 2*/NFS4.EXE"
RUNTIME_BASE = 0x8000F800

# Keep the global cop-country table stock.  This hook only post-processes the
# filename generated by the human/player car loading path.
GET_FILENAME_ADDR = 0x800AFB30
PLAYER_LIVERY_CAVE_OFF = 0x45B00
PLAYER_LIVERY_CAVE_LEN = 0x100
OLD_PLAYER_LIVERY_CAVE_OFF = 0x45CE8
OLD_PLAYER_LIVERY_CAVE_LEN = 0x78
PLAYER_GET_FILENAME_CALL_SITE = 0xA0584
GENERAL_GET_FILENAME_CALL_SITE = 0xA22B4

COP_INDEX_OFF = 0x108334
ORIGINAL_COP_INDEX = bytes.fromhex(
    "00 00 00 00 00"
    " 01 01 01 01 01"
    " 02 03 04 05 05"
    " 06 06 06 06 06"
    " 07 08 09 09 09"
    " 0a 0b 0c 0d 0e"
    " 00 00"
)
OLD_GLOBAL_COP_INDEX_PATCH = bytes.fromhex(
    "00 00 00 00 00"
    " 01 01 01 01 01"
    " 04 04 04 05 05"
    " 06 06 06 06 06"
    " 09 09 09 09 09"
    " 0c 0c 0c 0d 0e"
    " 00 00"
)

HUMAN_RACE_LIST_LOW = 0x0D0C


REG = {
    "zero": 0,
    "v0": 2,
    "v1": 3,
    "a0": 4,
    "a1": 5,
    "a2": 6,
    "t0": 8,
    "t1": 9,
    "t2": 10,
    "s4": 20,
    "sp": 29,
    "ra": 31,
}


def ins_i(op: int, rs: int, rt: int, imm: int) -> int:
    return (op << 26) | (rs << 21) | (rt << 16) | (imm & 0xFFFF)


def ins_r(rs: int, rt: int, rd: int, sh: int, fn: int) -> int:
    return (rs << 21) | (rt << 16) | (rd << 11) | (sh << 6) | fn


def ins_j(op: int, addr: int) -> int:
    return (op << 26) | ((addr >> 2) & 0x03FFFFFF)


def runtime(off: int) -> int:
    return RUNTIME_BASE + off


def pack(words: list[int]) -> bytes:
    return struct.pack("<" + "I" * len(words), *words)


def addiu(rt: str, rs: str, imm: int) -> int:
    return ins_i(0x09, REG[rs], REG[rt], imm)


def beq(rs: str, rt: str, pc: int, target: int) -> int:
    return ins_i(0x04, REG[rs], REG[rt], (target - (pc + 4)) >> 2)


def bne(rs: str, rt: str, pc: int, target: int) -> int:
    return ins_i(0x05, REG[rs], REG[rt], (target - (pc + 4)) >> 2)


def j(addr: int) -> int:
    return ins_j(0x02, addr)


def jal(addr: int) -> int:
    return ins_j(0x03, addr)


def jr(reg: str) -> int:
    return ins_r(REG[reg], 0, 0, 0, 0x08)


def lui(rt: str, imm: int) -> int:
    return ins_i(0x0F, 0, REG[rt], imm)


def lw(rt: str, off: int, rs: str) -> int:
    return ins_i(0x23, REG[rs], REG[rt], off)


def lbu(rt: str, off: int, rs: str) -> int:
    return ins_i(0x24, REG[rs], REG[rt], off)


def sb(rt: str, off: int, rs: str) -> int:
    return ins_i(0x28, REG[rs], REG[rt], off)


def sw(rt: str, off: int, rs: str) -> int:
    return ins_i(0x2B, REG[rs], REG[rt], off)


def nop() -> int:
    return 0


def old_player_livery_cave(
    done_delta: int = 0x68,
    bmw_delta: int = 0x5C,
    country_offset: int = 0x0003,
    diablo_country: int = ord("U"),
    bmw_country: int = ord("G"),
) -> bytes:
    pc = runtime(OLD_PLAYER_LIVERY_CAVE_OFF)
    done = pc + done_delta
    bmw = pc + bmw_delta
    words = [
        addiu("sp", "sp", -12),
        sw("ra", 0x0000, "sp"),
        sw("a0", 0x0004, "sp"),
        sw("a1", 0x0008, "sp"),
        jal(GET_FILENAME_ADDR),
        nop(),
        lw("t0", 0x0288, "s4"),
        lui("t1", 0x8011),
        lw("t1", HUMAN_RACE_LIST_LOW, "t1"),
        nop(),
        bne("t0", "t1", pc + 0x28, done),
        nop(),
        lw("t0", 0x0008, "sp"),
        addiu("t1", "zero", 0x0018),
        beq("t0", "t1", pc + 0x38, bmw),
        addiu("t1", "zero", 0x001B),
        bne("t0", "t1", pc + 0x40, done),
        nop(),
        lw("t0", 0x0004, "sp"),
        addiu("t1", "zero", diablo_country),
        sb("t1", country_offset, "t0"),
        j(done),
        nop(),
        lw("t0", 0x0004, "sp"),
        addiu("t1", "zero", bmw_country),
        sb("t1", country_offset, "t0"),
        lw("ra", 0x0000, "sp"),
        jr("ra"),
        addiu("sp", "sp", 12),
    ]
    return pack(words).ljust(OLD_PLAYER_LIVERY_CAVE_LEN, b"\x00")


def player_livery_cave(
    bmw_code: bytes = b"BMW",
    diablo_code: bytes = b"DBL",
    porsche_code: bytes | None = None,
    bmw_country: int = ord("g"),
    diablo_country: int = ord("u"),
    porsche_write_char: int = ord("X"),
    code_offset: int = 0x0003,
    country_offset: int = 0x0002,
    porsche_code_offset: int = 0x0002,
    porsche_write_offset: int = 0x0002,
) -> bytes:
    pc = runtime(PLAYER_LIVERY_CAVE_OFF)
    check_diablo = pc + 0x58
    check_porsche = pc + 0x90
    done = pc + (0x90 if porsche_code is None else 0xD0)
    words = [
        addiu("sp", "sp", -8),
        sw("ra", 0x0000, "sp"),
        sw("a0", 0x0004, "sp"),
        jal(GET_FILENAME_ADDR),
        nop(),
        lw("t0", 0x0004, "sp"),
        lbu("t1", code_offset, "t0"),
        addiu("t2", "zero", bmw_code[0]),
        bne("t1", "t2", pc + 0x20, check_diablo),
        nop(),
        lbu("t1", code_offset + 1, "t0"),
        addiu("t2", "zero", bmw_code[1]),
        bne("t1", "t2", pc + 0x30, done),
        nop(),
        lbu("t1", code_offset + 2, "t0"),
        addiu("t2", "zero", bmw_code[2]),
        bne("t1", "t2", pc + 0x40, done),
        nop(),
        addiu("t1", "zero", bmw_country),  # BMW M5 Cop -> zzgBMW
        sb("t1", country_offset, "t0"),
        j(done),
        nop(),
        lbu("t1", code_offset, "t0"),
        addiu("t2", "zero", diablo_code[0]),
        bne("t1", "t2", pc + 0x60, done if porsche_code is None else check_porsche),
        nop(),
        lbu("t1", code_offset + 1, "t0"),
        addiu("t2", "zero", diablo_code[1]),
        bne("t1", "t2", pc + 0x70, done if porsche_code is None else check_porsche),
        nop(),
        lbu("t1", code_offset + 2, "t0"),
        addiu("t2", "zero", diablo_code[2]),
        bne("t1", "t2", pc + 0x80, done if porsche_code is None else check_porsche),
        nop(),
        addiu("t1", "zero", diablo_country),  # Diablo SV Cop -> zzuDBL
        sb("t1", country_offset, "t0"),
    ]
    if porsche_code is not None:
        words.extend(
            [
                j(done),
                nop(),
                lbu("t1", porsche_code_offset, "t0"),
                addiu("t2", "zero", porsche_code[0]),
                bne("t1", "t2", pc + 0x98, done),
                nop(),
                lbu("t1", porsche_code_offset + 1, "t0"),
                addiu("t2", "zero", porsche_code[1]),
                bne("t1", "t2", pc + 0xA8, done),
                nop(),
                lbu("t1", porsche_code_offset + 2, "t0"),
                addiu("t2", "zero", porsche_code[2]),
                bne("t1", "t2", pc + 0xB8, done),
                nop(),
                addiu("t1", "zero", porsche_write_char),
                sb("t1", porsche_write_offset, "t0"),
            ]
        )
    words.extend(
        [
            lw("ra", 0x0000, "sp"),
            jr("ra"),
            addiu("sp", "sp", 8),
        ]
    )
    return pack(words).ljust(PLAYER_LIVERY_CAVE_LEN, b"\x00")


def find_default_exe() -> Path:
    hits = list(Path(".").glob(DEFAULT_EXE_GLOB))
    if len(hits) != 1:
        raise SystemExit(f"expected one {DEFAULT_EXE_GLOB}, found {len(hits)}")
    return hits[0]


def patch_at(data: bytearray, off: int, old_options: list[bytes], new: bytes, name: str, apply: bool) -> None:
    actual = bytes(data[off : off + len(new)])
    if actual == new:
        print(f"{name}: already patched at 0x{off:X}")
        return
    if actual not in old_options:
        expected = " or ".join(x.hex(" ") for x in old_options)
        raise SystemExit(f"{name}: unexpected bytes at 0x{off:X}: {actual.hex(' ')}; expected {expected}")
    print(f"{name}: patch 0x{off:X}: {actual.hex(' ')} -> {new.hex(' ')}")
    if apply:
        data[off : off + len(new)] = new


def apply_patch(path: Path, apply: bool, revert: bool) -> None:
    original = path.read_bytes()
    data = bytearray(original)

    cave = player_livery_cave()
    old_uppercase_cave = player_livery_cave(
        bmw_code=b"BMW",
        diablo_code=b"DBL",
        porsche_code=None,
        bmw_country=ord("G"),
        diablo_country=ord("U"),
        code_offset=0x0004,
        country_offset=0x0003,
    )
    old_lowercase_wrong_offsets_cave = player_livery_cave(
        bmw_code=b"bmw",
        diablo_code=b"dbl",
        porsche_code=None,
        bmw_country=ord("g"),
        diablo_country=ord("u"),
        code_offset=0x0004,
        country_offset=0x0003,
    )
    old_correct_two_rule_cave = player_livery_cave(porsche_code=None)
    old_wrong_cpr_porsche_cave = player_livery_cave(
        porsche_code=b"CPR",
        porsche_write_char=ord("g"),
        porsche_code_offset=0x0003,
        porsche_write_offset=0x0002,
    )
    old_wrong_x993_porsche_cave = player_livery_cave(
        porsche_code=b"X99",
        porsche_write_char=ord("P"),
        porsche_code_offset=0x0002,
        porsche_write_offset=0x0002,
    )
    old_p993_to_x993_porsche_cave = player_livery_cave(
        porsche_code=b"P99",
        porsche_write_char=ord("X"),
        porsche_code_offset=0x0002,
        porsche_write_offset=0x0002,
    )
    old_wrong_cmr_porsche_cave = player_livery_cave(
        porsche_code=b"CMR",
        porsche_write_char=ord("g"),
        porsche_code_offset=0x0002,
        porsche_write_offset=0x0002,
    )
    old_buggy_cave = old_player_livery_cave(
        done_delta=0x58,
        bmw_delta=0x4C,
        country_offset=0x0002,
        diablo_country=ord("u"),
        bmw_country=ord("g"),
    )
    old_wrong_country_offset_cave = old_player_livery_cave(
        country_offset=0x0002,
        diablo_country=ord("u"),
        bmw_country=ord("g"),
    )
    old_current_cave = old_player_livery_cave()
    original_call = pack([jal(GET_FILENAME_ADDR)])
    patched_call = pack([jal(runtime(PLAYER_LIVERY_CAVE_OFF))])
    old_patched_call = pack([jal(runtime(OLD_PLAYER_LIVERY_CAVE_OFF))])

    patch_at(
        data,
        COP_INDEX_OFF,
        [ORIGINAL_COP_INDEX, OLD_GLOBAL_COP_INDEX_PATCH],
        ORIGINAL_COP_INDEX,
        "restore global R3DCar_CopIndex table",
        apply,
    )

    patch_at(
        data,
        PLAYER_GET_FILENAME_CALL_SITE,
        [original_call, old_patched_call, patched_call],
        original_call if revert else patched_call,
        f"player-only cop livery call hook 0x{PLAYER_GET_FILENAME_CALL_SITE:X}",
        apply,
    )

    patch_at(
        data,
        GENERAL_GET_FILENAME_CALL_SITE,
        [original_call, old_patched_call],
        original_call,
        f"restore general R3DCar filename call 0x{GENERAL_GET_FILENAME_CALL_SITE:X}",
        apply,
    )

    patch_at(
        data,
        PLAYER_LIVERY_CAVE_OFF,
        [
            b"\x00" * PLAYER_LIVERY_CAVE_LEN,
            old_uppercase_cave,
            old_lowercase_wrong_offsets_cave,
            old_correct_two_rule_cave,
            old_wrong_cpr_porsche_cave,
            old_wrong_x993_porsche_cave,
            old_p993_to_x993_porsche_cave,
            old_wrong_cmr_porsche_cave,
            cave,
        ],
        b"\x00" * PLAYER_LIVERY_CAVE_LEN if revert else cave,
        "player-only cop livery cave",
        apply,
    )

    patch_at(
        data,
        OLD_PLAYER_LIVERY_CAVE_OFF,
        [b"\x00" * OLD_PLAYER_LIVERY_CAVE_LEN, old_buggy_cave, old_wrong_country_offset_cave, old_current_cave],
        b"\x00" * OLD_PLAYER_LIVERY_CAVE_LEN,
        "clear old player-only cop livery cave",
        apply,
    )

    if apply and bytes(data) != original:
        backup = path.with_name(path.name + BACKUP_SUFFIX)
        if not backup.exists():
            backup.write_bytes(original)
        path.write_bytes(data)
        print(f"done: patched {path}")
    elif not apply:
        print("dry run only; pass --apply to write changes")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Patch PROD2 NFS4.EXE: player-only BMW/Diablo cop livery override."
    )
    parser.add_argument("--exe", type=Path, help="Path to PROD2 NFS4.EXE")
    parser.add_argument("--apply", action="store_true", help="Write patched EXE")
    parser.add_argument("--revert", action="store_true", help="Remove player-only livery hook")
    args = parser.parse_args()

    apply_patch(args.exe or find_default_exe(), args.apply, args.revert)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
